name: Build and Push to Container Registry Production

on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY: 730335533085.dkr.ecr.ca-central-1.amazonaws.com

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@main
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          DNS_PROXY_LOGANALYTICSSHAREDKEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::730335533085:role/ai-answers-apply
          role-session-name: AIAnswersGitHubActions
          aws-region: "ca-central-1"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Build container
        working-directory: ./
        run: |
          docker build \
          -t $REGISTRY/ai-answers-prod:$GITHUB_SHA-`date '+%Y-%m-%d'` \
          -t $REGISTRY/ai-answers-prod:latest .

      - name: Push containers to Amazon ECR
        working-directory: ./
        run: |
          docker push $REGISTRY/ai-answers-prod:$GITHUB_SHA-`date '+%Y-%m-%d'`
          docker push $REGISTRY/ai-answers-prod:latest

      - name: Restart ECS
        run: |
          aws ecs update-service --cluster ai-answers-prod-cluster --service ai-answers-prod-app-service --force-new-deployment > /dev/null 2>&1

      - name: Wait for ECS Stability
        id: ecs_wait
        continue-on-error: true
        run: |
          echo "Wait for 15 minutes for ECS to stabilize.."
          sleep 300 # Sleep for 5 minutes. The ecs wait command waits for an additional 10 minutes
          aws ecs wait services-stable \
            --cluster ai-answers-prod-cluster \
            --services ai-answers-prod-app-service

      - name: Slack Notify Failure
        if: steps.ecs_wait.outcome == 'failure'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "‚ùå ECS deployment for ai-answers production failed to stabilize."}' \
          ${{ secrets.SLACK_WEBHOOK_URL}}

      - name: Report deployment to Sentinel
        if: steps.ecs_wait.outcome == 'success'
        uses: cds-snc/sentinel-forward-data-action@main
        with:
          input_data: '{"product": "ai-answers", "version": "${{ github.sha }}", "repository": "${{ github.repository }}", "environment": "production"}'
          log_type: CDS_Product_Deployment_Data
          log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

      - name: Docker generate SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@34794baf2af592913bb5b51d8df4f8d0acc49b6f # v3.2.0
        env:
          TRIVY_DB_REPOSITORY: ${{ vars.TRIVY_DB_REPOSITORY }}
        with:
          docker_image: "${{ env.REGISTRY }}/ai-answers-prod:latest"
          dockerfile_path: "./Dockerfile"
          sbom_name: "ai-answers-prod"
          token: "${{ secrets.GITHUB_TOKEN }}"
